### ISSUE TITLE
Plan to support other field type

### ISSUE THREAD

**Issue by ghost** [inetis-ch/oc-ListSwitch#2]
Hello,

I wonder if there is a plan to support others field types like textfields, dropdown etc...

Cause a module that would allow inline editing for specific fields directly on backend list would be awesome !

I think about the addition of a custom option in column.yaml file, for example if you add :

    editable: true

To any column type, it transform it to an inline editing element.

**Comment by pvullioud** [comment]
Hi,
Thanks for your feedback. We are not planning to add this kind of features to this plugin.
You can have a look to https://github.com/yajra/laravel-datatables and https://datatables.net
