### ISSUE TITLE
Override sortable feature

### ISSUE THREAD

**Issue by patosG** [inetis-ch/oc-ListSwitch#4]
thanks for the excellent plugin
To preserve the sortable feature in plugin.php boot, there should be 
`if (isset($config['sortable'])) {
                    $column['sortable'] = $config['sortable'];
                }`

like it is for the label.
(could be for all config parameters actually)

**Comment by shiftaltd** [comment]
could be for all config parameters actually

**Comment by roojai** [comment]
thanks! I used this to fix "invisible" settings too: 

if (isset($config['invisible'])) { $column['invisible'] = $config['invisible']; }

**Comment by patosG** [comment]
Any chance to get that on the next release?

**Comment by ChVuagniaux** [comment]
Thanks for the report and sorry for the long delay.

From version 1.0.3 (released just now) all column config are now preserved.
