### ISSUE TITLE
[Question] - Compatible with relationship list

### ISSUE THREAD

**Issue by damsfx** [inetis-ch/oc-ListSwitch#7]
Hi,  
Great plugin that's work like a charme ... Thanks, great idea !  

However, I have a problem with the relationship lists.  
If I try to use the switch on relationship lists I get an error.`

In my case Vehicle and Equipment models with a pivot table that contains a boolean column to set the equipment as "top list".

````
    pivot[is_top]:
        label: Top
        type: inetis-list-switch
````

Maybe because I'm trying to change a value on the pivot table !?

**Comment by ChVuagniaux** [comment]
Hi, 

Sadly a current limitation of this plugin is that it's not able to work automatically for relations.

For this kind of case you have to create a custom ajax handler in your controller and specify his name on the `request` attribute of your column config.

Example: 

```php
<?php 

class Accounts extends Controller
{
    ...

    /**
     * Publish / Unpublish Channel
     */
    public function preview_onSwitchChannelPublished()
    {
        if (empty($id = post('id'))) {
            Flash::error('Following parameter is required : id');

            return;
        }

        // replace this by your own logic for change the status of your pivot
        $channel = Channel::find($id);
        $channel->published = !$channel->published;
        $channel->save();

        $this->initForm($channel->account);
        $this->initRelation($channel->account, 'channels');

        return $this->relationRefresh('channels');
    }
}
```

```yaml
columns:

    ...

    published:
        label: Published
        type: inetis-list-switch
        request: onSwitchChannelPublished
```

**Comment by arrcorona** [comment]
@ChVuagniaux thanks it works.
